// Auto-skill synthesis. After a cycle that crosses the tool-use threshold,
// BajaClaw asks a lightweight backend call to look at the (task, response,
// tool sequence) and emit a SKILL.md written directly to the user skills
// dir (~/.bajaclaw/skills/<name>/). Skills are active immediately with no
// manual promotion step.
//
// Inspired by the "create a skill after complex tasks" pattern popularized
// by agents like Hermes. Our implementation is our own.
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { userSkillsDir } from "../paths.js";
import { runOnce } from "../claude.js";
import type { ClaudeEvent } from "../types.js";
import type { Logger } from "../logger.js";

export interface AutoSkillConfig {
  enabled: boolean;
  minToolUses: number;      // threshold to trigger synthesis
  maxPerDay: number;         // cap candidates/day to avoid noise
}

export const AUTO_SKILL_DEFAULT: AutoSkillConfig = {
  enabled: true,
  // Conservative: only fire after genuinely complex cycles. Tune up for
  // more noise; tune down for more capture.
  minToolUses: 6,
  maxPerDay: 5,
};

export interface AutoSkillInput {
  cycleId: number;
  task: string;
  response: string;
  events: ClaudeEvent[];
  cfg?: Partial<AutoSkillConfig>;
}

export interface AutoSkillResult {
  wrote: string | null;
  reason?: string;
}

const SYNTH_PROMPT = `You just watched an agent complete a task through tool use. Your job is to
decide whether the procedure it used is worth saving as a reusable skill. A
good skill captures a repeatable procedure - not a one-off answer.

If it is worth saving, output a SKILL.md file as plain markdown, starting
with a YAML frontmatter block. Use this exact shape:

---
name: <kebab-case-name>
description: <one sentence - what this skill accomplishes>
version: 0.1.0
tools: [<inferred tool list>]
triggers: [<1-3 phrases that should trigger this skill>]
effort: low|medium|high
auto_generated: true
---

## When to use
<when this procedure applies, in 1-3 bullet points>

## Quick reference
<3-5 lines of the most important facts>

## Procedure
1. First step
2. Second step
3. ...

## Pitfalls
- <common mistakes to avoid>

## Verification
- <how to confirm the procedure worked>

If the task was trivial, a one-off question, or the procedure is too
specific to be reusable, output the single word NONE and nothing else.

<task>
{{TASK}}
</task>

<tool_sequence>
{{TOOLS}}
</tool_sequence>

<response>
{{RESPONSE}}
</response>`;

export async function synthesize(
  input: AutoSkillInput,
  log?: Logger,
): Promise<AutoSkillResult> {
  const cfg = { ...AUTO_SKILL_DEFAULT, ...(input.cfg ?? {}) };
  if (!cfg.enabled) return { wrote: null, reason: "disabled" };

  const toolUses = countToolUses(input.events);
  if (toolUses < cfg.minToolUses) {
    return { wrote: null, reason: `below threshold (${toolUses}/${cfg.minToolUses})` };
  }

  if (overDailyCap(cfg.maxPerDay)) {
    return { wrote: null, reason: `daily cap reached (${cfg.maxPerDay})` };
  }

  const tools = summarizeToolSequence(input.events);
  // Tighter caps than before to keep the synthesis call cheap.
  const prompt = SYNTH_PROMPT
    .replace("{{TASK}}", input.task.slice(0, 1500))
    .replace("{{TOOLS}}", tools)
    .replace("{{RESPONSE}}", input.response.slice(0, 3000));

  const r = await runOnce(prompt, {
    model: "claude-sonnet-4-6",
    effort: "medium",
    printMode: true,
    disallowedTools: ["Read", "Write", "Edit", "Bash", "Grep", "Glob", "WebSearch", "WebFetch"],
  });

  if (!r.ok || !r.text) return { wrote: null, reason: "synth call failed" };
  const text = r.text.trim();
  if (text === "NONE" || !text.startsWith("---")) {
    return { wrote: null, reason: "no reusable procedure detected" };
  }

  const name = extractName(text) ?? `auto-${input.cycleId}-${Date.now()}`;
  const dir = join(userSkillsDir(), name);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  const path = join(dir, "SKILL.md");
  writeFileSync(path, ensureMarkedAutoGenerated(text, input.cycleId));

  log?.info("auto-skill.wrote", { name, path, cycleId: input.cycleId, toolUses });
  return { wrote: path };
}

export function countToolUses(events: ClaudeEvent[]): number {
  return events.filter((e) => e.type === "tool_use").length;
}

function summarizeToolSequence(events: ClaudeEvent[]): string {
  const tools = events
    .filter((e) => e.type === "tool_use")
    .map((e, i) => {
      const raw = (e as unknown as { name?: unknown }).name;
      const name = typeof raw === "string" ? raw : "tool";
      return `${i + 1}. ${name}`;
    });
  return tools.join("\n") || "(no tool calls)";
}

function extractName(text: string): string | null {
  const m = text.match(/^name:\s*([a-zA-Z][\w-]*)/m);
  return m?.[1] ?? null;
}

function ensureMarkedAutoGenerated(text: string, cycleId: number): string {
  if (/auto_generated:\s*true/.test(text)) return text;
  // Inject into frontmatter.
  const m = text.match(/^---\s*\n([\s\S]*?)\n---\s*\n/);
  if (!m) return text;
  const injected = m[0].replace(
    "---\n",
    `---\nauto_generated: true\nsource_cycle_id: ${cycleId}\ncreated_at: ${new Date().toISOString()}\n`,
  );
  return injected + text.slice(m[0].length);
}

function overDailyCap(maxPerDay: number): boolean {
  try {
    const dir = userSkillsDir();
    if (!existsSync(dir)) return false;
    const { readdirSync, statSync, readFileSync } = require("node:fs") as typeof import("node:fs");
    const today = new Date().toISOString().slice(0, 10);
    let count = 0;
    for (const entry of readdirSync(dir)) {
      try {
        const skillFile = join(dir, entry, "SKILL.md");
        const s = statSync(skillFile);
        if (!s.isFile() || s.mtime.toISOString().slice(0, 10) !== today) continue;
        const content = readFileSync(skillFile, "utf8");
        if (/auto_generated:\s*true/.test(content)) count++;
      } catch { /* skip */ }
    }
    return count >= maxPerDay;
  } catch { return false; }
}
