// Build the <available_skills> block injected into every cycle's
// system prompt. Replaces the per-cycle LLM matcher.
//
// Output: a flat index `name: <truncated description>` grouped by
// category. The agent reads full bodies on demand via skill_view.

import { createHash } from "node:crypto";
import { statSync } from "node:fs";
import { loadAllSkills } from "./loader.js";
import { readSidecar } from "./usage.js";
import type { Skill, SkillUsageEntry } from "../types.js";

export interface SkillsIndex {
  text: string;
  skills: Array<{ name: string; description: string; category: string }>;
  manifestHash: string;
}

const MAX_DESC_LEN = 120;
const CATEGORY_ORDER = ["General", "Setup", "Auto-generated"];

export function buildSkillsIndex(profile: string, allowedTools: string[] = []): SkillsIndex {
  const all = loadAllSkills(profile);
  const sidecar = readSidecar(profile);
  const visible = all.filter((s) => isVisible(s, sidecar.skills[s.name], allowedTools));

  const grouped = groupByCategory(visible);

  const lines: string[] = [];
  lines.push("<available_skills>");
  lines.push("The following skills are installed for this profile. Each line is `name: description`.");
  lines.push("To use a skill, call skill_view(name) to read its full content, then follow it.");
  lines.push("");

  for (const cat of CATEGORY_ORDER) {
    const items = grouped.get(cat);
    if (!items || items.length === 0) continue;
    lines.push(`# ${cat}`);
    for (const s of items) {
      lines.push(`- ${s.name}: ${truncate(s.description ?? "", MAX_DESC_LEN)}`);
    }
    lines.push("");
  }

  // Anything outside the canonical order (rare; future custom categories).
  for (const [cat, items] of grouped) {
    if (CATEGORY_ORDER.includes(cat) || items.length === 0) continue;
    lines.push(`# ${cat}`);
    for (const s of items) {
      lines.push(`- ${s.name}: ${truncate(s.description ?? "", MAX_DESC_LEN)}`);
    }
    lines.push("");
  }

  lines.push("Before answering, scan this list. If any skill is even partially relevant to the");
  lines.push("task, you MUST call skill_view(name) to read its body and follow its instructions.");
  lines.push("Err on the side of viewing.");
  lines.push("");
  lines.push("If during a cycle you discover a non-trivial reusable procedure, save it via");
  lines.push("skill_manage(action=\"create\"). Don't wait to be asked.");
  lines.push("</available_skills>");

  const text = lines.join("\n");
  const manifestHash = computeManifestHash(visible);
  const skills = visible.map((s) => ({
    name: s.name,
    description: s.description ?? "",
    category: categoryOf(s),
  }));
  return { text, skills, manifestHash };
}

function isVisible(skill: Skill, usage: SkillUsageEntry | undefined, allowedTools: string[]): boolean {
  if (usage?.state === "archived") return false;
  const tools = new Set(allowedTools);
  if (skill.requiresTools && skill.requiresTools.length > 0 && tools.size > 0) {
    for (const t of skill.requiresTools) if (!tools.has(t)) return false;
  }
  if (skill.fallbackForTools && skill.fallbackForTools.length > 0 && tools.size > 0) {
    for (const t of skill.fallbackForTools) if (tools.has(t)) return false;
  }
  return true;
}

function categoryOf(skill: Skill): string {
  if (skill.autoGenerated) return "Auto-generated";
  if (skill.name.startsWith("setup-")) return "Setup";
  return "General";
}

function groupByCategory(skills: Skill[]): Map<string, Skill[]> {
  const map = new Map<string, Skill[]>();
  for (const s of skills) {
    const cat = categoryOf(s);
    const arr = map.get(cat) ?? [];
    arr.push(s);
    map.set(cat, arr);
  }
  for (const arr of map.values()) arr.sort((a, b) => a.name.localeCompare(b.name));
  return map;
}

function truncate(s: string, max: number): string {
  const oneLine = s.replace(/\s+/g, " ").trim();
  if (oneLine.length <= max) return oneLine;
  return oneLine.slice(0, max - 1) + "…";
}

function computeManifestHash(skills: Skill[]): string {
  const sorted = [...skills].sort((a, b) => a.path.localeCompare(b.path));
  const h = createHash("sha256");
  for (const s of sorted) {
    let mtime = 0;
    let size = 0;
    try {
      const st = statSync(s.path);
      mtime = st.mtimeMs;
      size = st.size;
    } catch { /* ignore */ }
    h.update(`${s.path}|${mtime}|${size}\n`);
  }
  return h.digest("hex");
}
