// MCP tool: skill_view. Read a skill's full body on demand.

import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { loadAllSkills } from "./loader.js";
import { recordView } from "./usage.js";
import { readSidecar } from "./usage.js";

export interface SkillViewArgs {
  name: string;
}

export interface SkillViewResult {
  ok: boolean;
  status?: number;
  name?: string;
  description?: string;
  body?: string;
  path?: string;
  frontmatter?: Record<string, unknown>;
  state?: string;
  reason?: string;
}

export function skillView(args: SkillViewArgs, profile: string): SkillViewResult {
  const name = String(args?.name ?? "").trim();
  if (!name) return { ok: false, status: 400, reason: "name is required" };

  const all = loadAllSkills(profile);
  const skill = all.find((s) => s.name === name);
  if (!skill) {
    // Distinguish 410 (archived) from 404. Archived skills aren't loaded
    // by loadAllSkills; check sidecar to know if it used to exist.
    const sidecar = readSidecar(profile);
    const usage = sidecar.skills[name];
    if (usage?.state === "archived") {
      return { ok: false, status: 410, reason: `skill '${name}' is archived. Use skill_list({state:"archived"}) to see archived skills.` };
    }
    return { ok: false, status: 404, reason: `no skill named '${name}'` };
  }

  const skillFile = existsSync(join(skill.path, "SKILL.md"))
    ? join(skill.path, "SKILL.md")
    : join(skill.path, "skill.md");
  let raw: string;
  try {
    raw = readFileSync(skillFile, "utf8");
  } catch (e) {
    return { ok: false, status: 500, reason: `read failed: ${(e as Error).message}` };
  }

  const fmMatch = raw.match(/^---\s*\n([\s\S]*?)\n---\s*\n?([\s\S]*)$/);
  const body = fmMatch ? fmMatch[2]!.trim() : raw;
  const frontmatter: Record<string, unknown> = {
    name: skill.name,
    description: skill.description,
    version: skill.version,
    triggers: skill.triggers,
    effort: skill.effort,
    auto_generated: skill.autoGenerated,
  };

  const sidecar = readSidecar(profile);
  const state = sidecar.skills[name]?.state ?? "active";

  recordView(profile, name);

  return {
    ok: true,
    name: skill.name,
    description: skill.description,
    body,
    path: skill.path,
    frontmatter,
    state,
  };
}
