// MCP tool: skill_list. Filter the installed skill set by category /
// state. Backed by sidecar telemetry for state and pinned flag.

import { loadAllSkills } from "./loader.js";
import { readSidecar } from "./usage.js";
import { provenanceOf } from "./provenance.js";
import type { SkillState } from "../types.js";

export interface SkillListArgs {
  category?: string;
  state?: SkillState;
  includeArchived?: boolean;
}

export interface SkillListItem {
  name: string;
  description: string;
  category: string;
  state: SkillState;
  pinned: boolean;
  provenance: string;
  last_used_at: string | null;
  last_viewed_at: string | null;
  use_count: number;
  view_count: number;
}

function categoryOf(name: string, autoGenerated: boolean | undefined): string {
  if (autoGenerated) return "Auto-generated";
  if (name.startsWith("setup-")) return "Setup";
  return "General";
}

export function skillList(args: SkillListArgs, profile: string): SkillListItem[] {
  const all = loadAllSkills(profile);
  const sidecar = readSidecar(profile);
  const out: SkillListItem[] = [];

  for (const s of all) {
    const usage = sidecar.skills[s.name];
    const state: SkillState = usage?.state ?? "active";
    if (!args.includeArchived && state === "archived") continue;
    if (args.state && state !== args.state) continue;
    const cat = categoryOf(s.name, s.autoGenerated);
    if (args.category && cat !== args.category) continue;
    out.push({
      name: s.name,
      description: s.description ?? "",
      category: cat,
      state,
      pinned: usage?.pinned ?? false,
      provenance: usage?.provenance ?? provenanceOf(s, profile),
      last_used_at: usage?.last_used_at ?? null,
      last_viewed_at: usage?.last_viewed_at ?? null,
      use_count: usage?.use_count ?? 0,
      view_count: usage?.view_count ?? 0,
    });
  }
  return out.sort((a, b) => a.name.localeCompare(b.name));
}
